version: '3'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/utilitydb
    depends_on:
      - mongodb

  client:
    build: ./client
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
